<?php
declare(strict_types=1);
namespace App;

final class Webhook {
    public static function handle(string $provider,string $publicId,string $raw): array {
        $stmt=Database::connection()->prepare('SELECT pc.*,a.id application_id FROM payment_connections pc JOIN applications a ON a.id=pc.application_id WHERE a.public_id=? AND pc.provider=? AND pc.active=1 LIMIT 1');$stmt->execute([$publicId,$provider]);$conn=$stmt->fetch();if(!$conn)Http::json(['success'=>false,'error'=>'Connection not found'],404);
        $secret=Crypto::decrypt($conn['webhook_secret_encrypted']);if(!self::valid($provider,$raw,$secret))Http::json(['success'=>false,'error'=>'Invalid signature'],401);$payload=json_decode($raw,true);if(!is_array($payload))Http::json(['success'=>false,'error'=>'Invalid payload'],400);
        $p=self::normalize($provider,$payload);if(!$p)return ['received'=>true,'ignored'=>true];
        Database::connection()->prepare('INSERT INTO payments(application_id,provider,provider_reference,customer_name,customer_email,plan_name,amount_minor,currency,status,paid_at,raw_payload) VALUES(?,?,?,?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE status=VALUES(status),amount_minor=VALUES(amount_minor),currency=VALUES(currency),customer_name=VALUES(customer_name),customer_email=VALUES(customer_email),plan_name=VALUES(plan_name),paid_at=VALUES(paid_at),raw_payload=VALUES(raw_payload),updated_at=NOW()')->execute([$conn['application_id'],$provider,$p['reference'],$p['name'],$p['email'],$p['plan'],$p['amount'],$p['currency'],$p['status'],$p['paid_at'],json_encode($payload,JSON_UNESCAPED_SLASHES)]);return ['received'=>true];
    }
    private static function valid(string $provider,string $raw,string $secret):bool {$header=$_SERVER['HTTP_STRIPE_SIGNATURE']??$_SERVER['HTTP_X_WEBHOOK_SIGNATURE']??$_SERVER['HTTP_X_PAYSTACK_SIGNATURE']??$_SERVER['HTTP_VERIF_HASH']??'';if($provider==='stripe'&&str_contains($header,'v1=')){preg_match('/v1=([a-f0-9]+)/',$header,$m);preg_match('/t=(\d+)/',$header,$t);return isset($m[1],$t[1])&&abs(time()-(int)$t[1])<300&&hash_equals($m[1],hash_hmac('sha256',$t[1].'.'.$raw,$secret));}if($provider==='flutterwave')return hash_equals($secret,$header);return hash_equals(hash_hmac('sha512',$raw,$secret),$header)||hash_equals(hash_hmac('sha256',$raw,$secret),$header);}
    private static function normalize(string $provider,array $x):?array {$d=$x['data']??$x['payload']??$x;$type=strtolower((string)($x['type']??$x['event']??$d['status']??''));$status=str_contains($type,'refund')?'refunded':(str_contains($type,'fail')?'failed':(str_contains($type,'pending')?'pending':'paid'));$ref=(string)($d['id']??$d['reference']??$d['tx_ref']??'');if($ref==='')return null;$customer=$d['customer']??$d['customer_details']??[];$amount=$d['amount']??$d['amount_paid']??$d['amount_received']??0;if(is_float($amount))$amount=(int)round($amount*100);return ['reference'=>$ref,'name'=>$customer['name']??trim(($customer['first_name']??'').' '.($customer['last_name']??''))?:null,'email'=>$customer['email']??$d['customer_email']??null,'plan'=>$d['plan']['name']??$d['metadata']['plan']??null,'amount'=>(int)$amount,'currency'=>strtoupper((string)($d['currency']??'USD')),'status'=>$status,'paid_at'=>$status==='paid'?date('Y-m-d H:i:s'):null];}
}

